module idl {
	interface BoardObserver {
		void update();
	};
	interface Board {
		long getCols();
		long getCard(in long col, in long row);
		void addBoardObserver(in BoardObserver myboardobserver);
		boolean removeSet(
			in long x1, in long y1,
			in long x2, in long y2,
			in long x3, in long y3
		);
	};
	interface Set {
		Board getBoard();
	};
};
